version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    restart: unless-stopped

    # Uncomment the following block if GPU support is required
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

    # Volumes to allow data persistence or sharing
    volumes:
      - ./app:/app
      - ./logs:/app/logs

    # Define environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    # Ports for accessing the app externally
    ports:
      - "8000:8000"

    # Optional GPU access support
    # Uncomment the following line for GPU support
    # runtime: nvidia

    # Add any dependencies to be installed at runtime if needed
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
